name: OCI image push

on:
  push:
      branches:
        - main
        - serrano-cc
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: [ self-hosted, "${{ matrix.archconfig }}", go]
    strategy:
      matrix:
        archconfig: [ "x86_64" ]
      fail-fast: false
    
    steps:
    - name: Cleanup previous jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    # - name: Display Go version
    #   run: |
    #     go version

    - name: Find SHA
      run: |
        if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
        then
          echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.ref}})" >> $GITHUB_ENV
        else
          echo "ARTIFACT_SHA=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        fi
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.nbfc.io/nubificus
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_SECRET }}
    - name: Check install!
      run: cosign version
    - name: Set up Docker Context for Buildx
      run: |
          docker context create builders || true
    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      with:
        version: latest
        endpoint: builders
    - name: Get Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: harbor.nbfc.io/nubificus/serrano/cc-gw-signed
        tags: |
                type=sha,prefix=nbfc-

    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@master
      with:
        context: .
        file: ./Dockerfile
        push: true
        #tags: harbor.nbfc.io/nubificus/cosigntest:${{env.ARTIFACT_SHA}}
        #images: harbor.nbfc.io/nubificus/cosigntest
        tags: ${{ steps.docker_meta.outputs.tags }}

    - name: Sign the published Docker image
      env:
        COSIGN_EXPERIMENTAL: "true"
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: ${{ steps.docker_meta.outputs.tags }}
      # run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
      run: |
        cosign sign --yes harbor.nbfc.io/nubificus/serrano/cc-gw-signed@${{steps.build-and-push.outputs.digest}} \
        -a "repo=${{github.repository}}" \
        -a "workflow=${{github.workflow}}" \
        -a "ref=${{github.sha}}" \
        -a "author=Nubificus LTD"
    - name: Clean up Docker Context for Buildx
      id: buildx-context-cleanup
      run: |
          docker context remove builders || true
